/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosTransporteRodoviarioRouteImport } from './routes/servicos.transporte-rodoviario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosTransporteRodoviarioRoute =
  ServicosTransporteRodoviarioRouteImport.update({
    id: '/servicos/transporte-rodoviario',
    path: '/servicos/transporte-rodoviario',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/servicos/transporte-rodoviario': typeof ServicosTransporteRodoviarioRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/servicos/transporte-rodoviario': typeof ServicosTransporteRodoviarioRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/servicos/transporte-rodoviario': typeof ServicosTransporteRodoviarioRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sobre' | '/servicos/transporte-rodoviario' | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sobre' | '/servicos/transporte-rodoviario' | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/sobre'
    | '/servicos/transporte-rodoviario'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SobreRoute: typeof SobreRoute
  ServicosTransporteRodoviarioRoute: typeof ServicosTransporteRodoviarioRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/transporte-rodoviario': {
      id: '/servicos/transporte-rodoviario'
      path: '/servicos/transporte-rodoviario'
      fullPath: '/servicos/transporte-rodoviario'
      preLoaderRoute: typeof ServicosTransporteRodoviarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SobreRoute: SobreRoute,
  ServicosTransporteRodoviarioRoute: ServicosTransporteRodoviarioRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
